const L={ru:{home:"Главная",features:"Возможности",pricing:"Прайс",download:"Скачать",login:"Войти",hero:"Fly Client — современный сайт клиента Minecraft с личным кабинетом, подписками, ключами и двумя вариантами загрузки.",downloadNow:"Скачать клиент",viewPrices:"Прайс",online:"Система онлайн",featuresTitle:"Возможности",f1:"Быстрый интерфейс",f1p:"Чистый современный дизайн без лишнего.",f2:"Личный кабинет",f2p:"Профиль, статус подписки и активация ключа.",f3:"Система ключей",f3p:"30, 180, 365 дней или навсегда.",f4:"RU / EN",f4p:"Переключение языка одним нажатием.",pricingTitle:"Прайс",coming:"СКОРО БУДЕТ ДОСТУПНО",days:"дней",year:"год",popular:"ПОПУЛЯРНЫЙ",forever:"Навсегда",buySoon:"Скоро будет",downloadTitle:"Скачать Fly Client",launcher:"Полноценный лаунчер для компьютера.",mod:"Обычный мод для Minecraft 1.21.11.",downloadSoon:"Скоро будет",accountTitle:"Твой аккаунт",accountText:"Войди или зарегистрируйся, чтобы управлять подпиской.",register:"Регистрация"},en:{home:"Home",features:"Features",pricing:"Pricing",download:"Download",login:"Login",hero:"Fly Client — a modern Minecraft client website with an account area, subscriptions, keys and two download options.",downloadNow:"Download client",viewPrices:"Pricing",online:"System online",featuresTitle:"Features",f1:"Fast interface",f1p:"A clean modern design without clutter.",f2:"Account area",f2p:"Profile, subscription status and key activation.",f3:"Key system",f3p:"30, 180, 365 days or forever.",f4:"RU / EN",f4p:"Switch language with one click.",pricingTitle:"Pricing",coming:"COMING SOON",days:"days",year:"year",popular:"POPULAR",forever:"Forever",buySoon:"Coming soon",downloadTitle:"Download Fly Client",launcher:"Standalone launcher for PC.",mod:"Regular mod for Minecraft 1.21.11.",downloadSoon:"Coming soon",accountTitle:"Your account",accountText:"Log in or register to manage your subscription.",register:"Register"}};
let lang=localStorage.getItem("flyLang")||"ru";
function tr(){document.querySelectorAll("[data-t]").forEach(e=>e.textContent=L[lang][e.dataset.t]);document.getElementById("lang").textContent=lang==="ru"?"RU / EN":"EN / RU";localStorage.setItem("flyLang",lang)}
document.getElementById("lang").onclick=()=>{lang=lang==="ru"?"en":"ru";tr()};
const modal=document.getElementById("modal"),body=document.getElementById("modalBody");
function show(type){let r=lang==="ru";body.innerHTML=`<div class="form"><h2>${type==="login"?(r?"Вход":"Login"):(r?"Регистрация":"Register")}</h2>${type==="register"?`<input placeholder="${r?"Никнейм":"Username"}"><input type="email" placeholder="Email">`:""}<input placeholder="${r?"Пароль":"Password"}" type="password"><button class="primary">${type==="login"?(r?"Войти":"Login"):(r?"Создать аккаунт":"Create account")}</button><p class="note">${r?"Интерфейс готов. Для настоящей регистрации нужен подключённый backend.":"The interface is ready. A backend is required for real registration."}</p></div>`;modal.classList.add("show")}
openLogin.onclick=()=>show("login");openLogin2.onclick=()=>show("login");openRegister.onclick=()=>show("register");close.onclick=()=>modal.classList.remove("show");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("show")};
document.querySelectorAll(".buy").forEach(x=>x.onclick=()=>alert(lang==="ru"?"Оплата будет подключена позже.":"Payments will be connected later."));
document.querySelectorAll(".unavailable").forEach(x=>x.onclick=()=>alert(lang==="ru"?"Файл клиента пока не опубликован.":"The client file has not been published yet."));
hamb.onclick=()=>{document.querySelector("nav").style.display=document.querySelector("nav").style.display==="flex"?"none":"flex"};
tr();