const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),Database=require("better-sqlite3"),crypto=require("crypto");
const app=express(),db=new Database("../database/fly.db"),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"CHANGE_ME_IN_PRODUCTION";
app.use(cors());app.use(express.json());
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS keys(id INTEGER PRIMARY KEY AUTOINCREMENT,key TEXT UNIQUE NOT NULL,days INTEGER,used_by INTEGER,created_at TEXT NOT NULL,expires_at TEXT);`);
function token(u){return jwt.sign({id:u.id,username:u.username,role:u.role},SECRET,{expiresIn:"7d"})}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch{return res.status(401).json({error:"Unauthorized"})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"Admin only"});next()}
app.get("/api/health",(req,res)=>res.json({ok:true,service:"Fly Client API"}));
app.post("/api/register",(req,res)=>{const {username,password}=req.body;if(!username||!password||password.length<6)return res.status(400).json({error:"Username and password (6+) required"});try{const hash=bcrypt.hashSync(password,10),r=db.prepare("INSERT INTO users(username,password,role,created_at) VALUES(?,?,?,?)").run(username,hash,"user",new Date().toISOString());const u={id:r.lastInsertRowid,username,role:"user"};res.json({token:token(u),user:u})}catch(e){res.status(409).json({error:"Username already exists"})}});
app.post("/api/login",(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE username=?").get(req.body.username);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).json({error:"Invalid credentials"});res.json({token:token(u),user:{id:u.id,username:u.username,role:u.role}})});
app.get("/api/me",auth,(req,res)=>res.json(req.user));
app.post("/api/admin/keys",auth,admin,(req,res)=>{const days=[30,180,365,null].includes(req.body.days)?req.body.days:30;const key="FLY-"+crypto.randomBytes(8).toString("hex").toUpperCase();const now=new Date();let exp=null;if(days){const d=new Date(now);d.setUTCDate(d.getUTCDate()+days);exp=d.toISOString()}db.prepare("INSERT INTO keys(key,days,created_at,expires_at) VALUES(?,?,?,?)").run(key,days,now.toISOString(),exp);res.json({key,days,expires_at:exp})});
app.get("/api/admin/keys",auth,admin,(req,res)=>res.json(db.prepare("SELECT id,key,days,used_by,created_at,expires_at FROM keys ORDER BY id DESC").all()));
app.post("/api/activate",auth,(req,res)=>{const k=db.prepare("SELECT * FROM keys WHERE key=?").get(req.body.key);if(!k)return res.status(404).json({error:"Key not found"});if(k.used_by)return res.status(409).json({error:"Key already used"});db.prepare("UPDATE keys SET used_by=? WHERE id=?").run(req.user.id,k.id);res.json({ok:true,days:k.days,expires_at:k.expires_at})});
app.listen(PORT,()=>console.log("Fly Client API on http://localhost:"+PORT));